### ISSUE TITLE
绝对定位元素的水平垂直居中的方法及原理

### ISSUE THREAD

**Issue by Plortinus** [Plortinus/blog#2]
# 水平垂直居中
[学习链接](http://www.zhangxinxu.com/wordpress/2013/11/margin-auto-absolute-%E7%BB%9D%E5%AF%B9%E5%AE%9A%E4%BD%8D-%E6%B0%B4%E5%B9%B3%E5%9E%82%E7%9B%B4%E5%B1%85%E4%B8%AD/)
1. 普通写法
```css
.element {
  width: 600px;
  height: 300px;
  position: absolute;
  top: 50%;
  left: 50%;
  margin-top: -150px;(自身高度的一半)
  margin-left: -300px;（自身宽度的一半）
}
```
缺点：计算margin值的时候，需要提前知道高宽。
2. CSS3写法，第一个写法的升级版
```css
.element {
  width: 600px; 
  height: 400px;
  position: absolute; 
  left: 50%; 
  top: 50%;
  transform: translate(-50%, -50%);    /* 50%为自身尺寸的一半 */
}
```
3. margin: auto方法
```css
.element {
    width: 600px; height: 400px;
    position: absolute; left: 0; top: 0; right: 0; bottom: 0;
    margin: auto;    /* 有了这个就自动居中了 */
}
```
## 原理

> 当一个绝对定位元素，其对立定位方向属性同时有具体定位数值的时候，流体特性就发生了。

什么是[流体特性](http://www.zhangxinxu.com/wordpress/2015/02/css-deep-understand-flow-bfc-column-two-auto-layout/)?

**Comment by Plortinus** [comment]
# 水平居中
1. 文字水平居中
```html
<div>你好,婉转喵!</div>
```
```css
div{
  text-align: center;
}
```
